### ISSUE TITLE
Celery Beat - RabbitMQ

### ISSUE THREAD

**Issue by afriapps** [praekeltfoundation/docker-django-bootstrap#82]
Hi, I am new to using docker and got this up and running in Azure with my Django project.
It's not clear how rabbitmq fits into this. I have celery setup and beat plus worker running, but cannot connect to rabbitmq:

Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused

Where am is this setup?

**Comment by JayH5** [comment]
Hi @afriapps 👋,

The Celery connection is configured using the [`broker_url` configuration option](http://docs.celeryproject.org/en/latest/userguide/configuration.html#conf-broker-settings) (see also [_Using RabbitMQ_](http://docs.celeryproject.org/en/latest/getting-started/brokers/rabbitmq.html)). How exactly this is set (environment variable vs Django settings) depends on your deployment.

I _think_ the easiest way is to just set the `CELERY_BROKER_URL` environment variable, which should work for Celery 3.1+, although I haven't configured a Celery instance in a little while so could be wrong 😅.

This isn't documented in django-bootstrap because it's really a Celery/Django thing that isn't specific to this Docker image.
